# Generated by Django 2.1.2 on 2023-02-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile', models.CharField(choices=[('cliente', 'Cliente'), ('veterinario', 'Veterinário')], max_length=11, null=True, verbose_name='Perfil')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Está ativo?')),
                ('staff', models.BooleanField(blank=True, default=False, verbose_name='É da equipe?')),
                ('admin', models.BooleanField(blank=True, default=False, verbose_name='Admin?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
