# Generated by Django 4.1.7 on 2023-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[("veterinario", "Veterinário"), ("cliente", "Cliente")],
                max_length=11,
                null=True,
                verbose_name="Perfil",
            ),
        ),
    ]
