# Generated by Django 4.1.7 on 2023-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cell_main", models.CharField(blank=True, max_length=11)),
                ("cell_contact", models.CharField(blank=True, max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("document", models.CharField(blank=True, max_length=21)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(blank=True, max_length=30)),
                ("zipcode", models.CharField(blank=True, max_length=11)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("PR", "PR"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("RS", "RS"),
                            ("SC", "SC"),
                            ("SE", "SE"),
                            ("SP", "SP"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
