# Generated by Django 4.1.7 on 2023-02-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("register", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modificado em"),
                ),
                (
                    "nf",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="nota fiscal"
                    ),
                ),
                (
                    "movimento",
                    models.CharField(
                        blank=True,
                        choices=[("e", "entrance"), ("x", "exit")],
                        max_length=1,
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtocoloEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modificado em"),
                ),
                ("estoque_atualizado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "operation",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=100
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("createdin", models.DateTimeField(auto_now_add=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.register",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EstoqueItens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("saldo", models.PositiveIntegerField(blank=True)),
                (
                    "estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="order.estoque",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="EstoqueEntrada",
            fields=[],
            options={
                "verbose_name": "estoque entrada",
                "verbose_name_plural": "estoque entrada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("order.estoque",),
        ),
        migrations.CreateModel(
            name="EstoqueSaida",
            fields=[],
            options={
                "verbose_name": "estoque saída",
                "verbose_name_plural": "estoque saída",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("order.estoque",),
        ),
    ]
